### ISSUE TITLE
go-fsrs 升级至 FSRSv4

### ISSUE THREAD

**Issue by L-M-Sherlock** [siyuan-note/riff#1]
https://github.com/open-spaced-repetition/go-fsrs/releases/tag/v1.0.0

这次升级主要改进了算法的公式，相对降低了 30% 的预测误差（相当于估计学习者记忆更准确了）

建议思源这边也更新一下依赖版本。我之后的优化器也会基于 FSRSv4 来做。

**Comment by 88250** [comment]
收到，感谢叶大。
