### ISSUE TITLE
Rating 相关问题

### ISSUE THREAD

**Issue by L-M-Sherlock** [siyuan-note/riff#2]
https://github.com/siyuan-note/riff/blob/c39d8f20d0c624f9120af6ff415e724d9c249762/store.go#L120-L125

这里的 Rating 是从 0 开始的。但在 FSRSv4 中，Rating 统一从 1 开始了。不知道这里会不会受到影响？以及持久化部分存的 Rating 和这里的有关吗？

**Comment by 88250** [comment]
感谢提醒，之前没有持久化数据，影响不大，我们把调用 repeat 的入参改改应该就行了。
