### ISSUE TITLE
有办法增添fsrs的自定义权重功能吗？

### ISSUE THREAD

**Issue by enshulv** [siyuan-note/riff#3]
叶哥那里现在支持根据用户的数据来自定义权重
似乎只需要修改store.params.W，要求用户输入一个17个元素的数组，然后增加一个设置，默认关闭需要的打开就可以了。
其次是可能需要添加一个卡片导出功能，以便让用户在长期使用后可以将卡片导出去优化自定义权重......不过这个比较麻烦，可能现在最简单的是适配一个已有的自定义权重供已经有了权重的迁移用户使用。
我不太会写go，也不太清楚是否有未知的问题，所以还是想先发个issue问一下，这是否可行呢？

**Comment by 88250** [comment]
参数应该是可以增加，但是目前没有时间加入配置项，如果急需的话只能通过修改源码再编译。

之前讨论过优化器，请参考 https://github.com/siyuan-note/siyuan/issues/8594
